# Markdown Editor Configuration
port: 4000

site:
  origin: http://localhost:4000
  view_transitions: true

# Design system
design:
  layers: [reset, base, components, utilities]
  inline_css: false

# Import map for client-side modules
import_map:
  app: /app/index.js

# Meta defaults
meta:
  title: Markdown Editor
  description: A pure client-side markdown editor with live preview
  viewport: width=device-width,initial-scale=1