# Markdown Editor Configuration
port: 4000

site:
  origin: http://localhost:4000
  view_transitions: true

# Server configuration for file operations
server:
  dir: server
  reload: true

# Design system
design:
  layers: [reset, base, components, utilities]
  inline_css: false

# Import map for client-side modules
import_map:
  app: /app/index.js

# Content processing
content:
  heading_ids: true
  sections: false

# Meta defaults
meta:
  title: Markdown Editor
  description: A web-based markdown editor with live preview
  viewport: width=device-width,initial-scale=1

# Linguix configuration (API key should be set via environment variable)
linguix:
  enabled: true
  # Set LINGUIX_API_KEY environment variable or update this field
  api_key: null